# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define :node1 do |node1|
        node1.vm.box = "ubuntu1404"
        node1.vm.hostname = "node1.fx-dev.net"
        node1.vm.network :private_network, :ip => "192.168.176.100"
        node1.vm.network :public_network, :bridge => "eth0"
        node1.vm.synced_folder ".", "/vagrant", disabled: true
    end

    config.vm.define :node2 do |node2|
        node2.vm.box = "ubuntu1404"
        node2.vm.hostname = "node2.fx-dev.net"
        node2.vm.network :private_network, :ip => "192.168.176.101"
        node2.vm.network :public_network, :bridge => "eth0"
        node2.vm.synced_folder ".", "/vagrant", disabled: true
    end

    config.vm.define :node3 do |node3|
        node3.vm.box = "ubuntu1404"
        node3.vm.hostname = "node3.fx-dev.net"
        node3.vm.network :private_network, :ip => "192.168.176.102"
        node3.vm.network :public_network, :bridge => "eth0"
        node3.vm.synced_folder ".", "/vagrant", disabled: true
    end


    config.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    config.vm.provision "shell", path: "install.sh"
end
