# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.define :node1 do |node1|
        node1.vm.box = "ubuntu1404"
        node1.vm.hostname = "master.fx-dev.com"
        node1.vm.network :private_network, :ip => "192.168.217.100"
        node1.vm.network :public_network, :bridge => "eth0"
        node1.vm.synced_folder ".", "/vagrant", disabled: true
        node1.vm.provision "shell", path: "install.sh"
    end

    config.vm.provider :virtualbox do |vb|
        vb.gui = false
        vb.customize ["modifyvm", :id, "--memory", "4096"]
        vb.customize ["modifyvm", :id, "--ioapic", "on"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    #config.vm.provision "shell", path: "install.sh"
end
