# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu1604"
  config.vm.hostname = "pica"

  config.vm.network "private_network", ip: "172.16.200.100"
  config.vm.network "public_network", bridge: "enp2s0"

  config.vm.synced_folder ".", "/vagrant", disabled: true
 
  config.vm.provider "virtualbox" do |vb|
     vb.gui = false
 
     vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
     vb.memory = 8192
  end
  config.vm.provision "shell", path: "install.sh"
end
